#!/usr/bin/env sage
from sage.all import *

# Exercise 2: NTT / INTT
# Ring: Z_17[X]/(X⁴ + 1), q=17, d=4
# Prerequisite: 17 ≡ 1 (mod 8), so a primitive 8th root of unity exists in Z_17

q = 17
d = 4
Zq = Integers(q)
R = PolynomialRing(Zq, 'X')
X = R.gen()
R_q = R.quotient(X**d + 1, 'x')
x = R_q.gen()

# 2a. Find the primitive 8th root of unity ω
# I.e. since Rq is over Z_q. Wanted to find X^d + 1 = 0.
# We first find X^d = 1, X \in Z_q^*
# Z_q^* = {1, ..., 16}, which is a cyclic group. First we find a generator
def find_generator_from_mul_group(q: int) -> int:
    # if q is prime, order is q-1.
    order = q-1
    # skip identity
    for g in range(2, order):
        generated_group = set([g**i % q for i in range(order)])
        # group generated by g is Z_q^*
        if len(generated_group) == order:
            return g
    raise ValueError("couldn't find generator for U_q")

#
# Find roots of X^d + 1 = 0
#
# Z_q^* = {1, 2, ..., 2^{q-1}}, so we know 2^16 = 1 mod q,
_order = q - 1
g = find_generator_from_mul_group(q)
assert g**_order % q == 1
nth = 2*d
# g^{order} = 1, we know X^{2d} = 1, order = q-1
# We want X^d + 1 = 0 -> X^d = -1 mod q -> X^{2d} = 1 mod q,
# so basically finding a primitive 8th roots of unity.
# Since g^{order} = 1 mod q and (g^2)^{order/2} = 1, mod q.
# We're then find all roots of unity X s.t. all X^4 + 1 = 0
# (w^t)^4 = -1 -> (w^4)^t = (-1)^t. t must be odd.
k = _order // nth
w = g ** k
assert w**nth % q == 1
roots = [w**i % q for i in range(nth) if i % 2 == 1]
assert len(set(roots)) == nth / 2

def gen_random_r_q() -> R_q:
    import random
    return sum([(random.randint(0, q-1)) * x**i for i in range(d)])

a = gen_random_r_q()

def get_odd(p: R_q) -> R_q:
    coeffs = p.list()
    return sum([v* x**(i // 2)for i, v in enumerate(coeffs) if i % 2 == 1])

def get_even(p: R_q) -> R_q:
    coeffs = p.list()
    return sum([v* x**(i // 2) for i, v in enumerate(coeffs) if i % 2 == 0])

a_odd = get_odd(a)
a_even = get_even(a)
# a(x) = x* a_odd(x^2) + a_even(x^2)
print(f"{a=}")
print(f"{a_odd=}")
print(f"{a_even=}")

# a(w)
res_a_w = R(a.lift())(w)
# a(w) = w* a_odd(w^2) + a_even(w^2)
res_a_w_from_odd_even = w * R(a_odd.lift())(w**2) + R(a_even.lift())(w**2)
assert res_a_w == res_a_w_from_odd_even, f"{res_a_w=}, {res_a_w_from_odd_even=}"


def find_root_brute_force():
    pass


# 2b. Implement NTT
# Given a(X) with coefficients [a0, a1, a2, a3], compute:
#   NTT(a) = [a(ω^1), a(ω^3), a(ω^5), a(ω^7)]
# Question: why odd powers?
# Hint: the roots of X^4 + 1 in Z_17 are exactly ω^1, ω^3, ω^5, ω^7


# 2c. Implement INTT
# Implement the inverse NTT. Verify that INTT(NTT(a)) = a


# 2d. Multiplication via NTT
# Verify: NTT(a * b) = NTT(a) ⊙ NTT(b) (pointwise multiplication)
# Compare with Exercise 1a result
