from sage.all import *

def setup_fake_pairing(r_bits=16, max_degree=1024):
    # 1. pick prime r (the group order)
    r = random_prime(2**r_bits)
    Fr = GF(r)  # scalar field

    # 2. pick p = k*r + 1, so Fp contains r-th roots of unity
    k = 2
    while True:
        p = k*r + 1
        if is_prime(p):
            break
        k += 1

    Fp = GF(p)
    g = Fp.multiplicative_generator()

    # ω is generator of subgroup of order r
    omega = g**k

    # 3. define groups
    # G1 = additive group over Fr
    # G2 = additive group over Fr
    # GT = multiplicative subgroup generated by ω
    def pairing_func(x, y):
        return omega ** (int(x) * int(y))

    G1 = Fr
    G2 = Fr
    tau = Fr.random_element()
    G1_srs = [tau**i for i in range(max_degree + 1)]

    return Fr, G1, G2, G1_srs, pairing_func


Fr, G1, G2, G1_srs, pairing_func = setup_fake_pairing()

print(f"G1: {G1}")
print(f"G2: {G2}")
print(f"pairing_func: {pairing_func}")

X = PolynomialRing(Fr, 'X').gen()

# Secret polynomial
f = 3*X**2 + 5*X + 7
print(f"f: {f}")
print(f"f.coefficients(): {f.coefficients()}")

def commit_polynomial(f, G1_srs):
    return sum(f[i] * G1_srs[i] for i in range(len(f.coefficients())))

com = commit_polynomial(f, G1_srs)
print(f"com: {com}")

# Verifier choose a random z
z = Fr.random_element()
print(f"z: {z}")
