#!/usr/bin/env sage
from sage.all import *


# Z_q^* = {1, ..., 16}, which is a cyclic group and exists a generator.
def find_generator_from_mul_group(q: int):
    # if q is prime, order is q-1.
    order = q-1
    Fq = GF(q)
    # skip identity
    for g in range(2, order):
        generated_group = set([Fq(g**i) for i in range(order)])
        # group generated by g is Z_q^*
        if len(generated_group) == order:
            return Fq(g)
    assert g**(q - 1) == 1
    raise ValueError("couldn't find generator for U_q")


def find_root_of_unity(g: int, d: int, q: int) -> int:
    assert g**(q - 1) == 1
    return g**((q-1) // d)


#
# NTT with X^d - 1
#

def _ntt_std(coeffs: list[int], omega: int, q: int) -> list[int]:
    """
    NTT with modulus polynomial X^d-1
    """
    d = len(coeffs)
    assert (q-1) % d == 0
    Fq = GF(q)
    coeffs = [Fq(v) for v in coeffs]
    omega = Fq(omega)
    # recursion invairant
    # ntt(f, w) = ntt(f_even, w^2) + w*ntt(w_odd, w^2)
    cur_d = len(coeffs)
    if cur_d == 1:
        return coeffs
    roots = [omega**i for i in range(cur_d)]

    f_even = [v for i, v in enumerate(coeffs) if i % 2 == 0]
    f_odd = [v for i, v in enumerate(coeffs) if i % 2 == 1]
    # f_even = sum([v* x**(i // 2) for i, v in enumerate(_coeffs) if i % 2 == 0])
    # f_odd = sum([v* x**(i // 2)for i, v in enumerate(_coeffs) if i % 2 == 1])
    # d = 4
    # v 1     -square->   1
    # v w     -square->   w^2
    #   w^2   -square->   w^4=1  (= 2 % (d/2) = 0)
    #   w^3   -square->   w^6=w^2 (= 3 % (d/2) = 1)
    # since (w^i)^2 = w^{i % {d/2}}, we only need to calculate f_o, f_e for the first half ([:d/2]),
    # and they can be reused for calculating the final results.
    even_evals = _ntt_std(f_even, omega**2, q)
    odd_evals = _ntt_std(f_odd, omega**2, q)

    evals = [0] * cur_d
    for i in range(cur_d):
        w = roots[i]
        w_square_eval_idx = i % (cur_d // 2)
        # f(w) = f_e(w^2) + w * f_o(w^2)
        evals[i] = even_evals[w_square_eval_idx] + w * odd_evals[w_square_eval_idx]
    return evals


def _intt_std(evals: list[int], omega: int, q: int) -> list[int]:
    """
    evaluation form <-> coefficient form is matrix multiplications
        coeff -> eval: [f(w^0), f(w^1)]^T = V * [f_0, f_1]^T
    since V is a dxd rank d matrix, it has inverse V^{-1}, and we get
        eval -> coeff: [f_0, f_1]^T = V^{-1} * [f(w^0), f(w^1)]^T

    V = [[1, 1], [1, w^1]] and V^{-1} = 1/d*[[1, 1], [1, w^{-1}]]
    It's just a matter of w^i -> w^{-i} and times 1/d
    If we treat eval ([f(w^0), f(w^1)]) as a polynomial, INTT is a
    linear transform with w^{-i} while the result should be timed `1/d`.

    NTT:    evals = ntt(coeffs, [1, w, ...])
    INTT:   coeffs = (1/d) * ntt(evals, [1, w^{-1}, ...])
    """
    d = len(evals)
    assert (q-1) % d == 0
    Fq = GF(q)
    # Treat evaluations as polynomial
    # Perform NTT with w^{-i}
    inv_omega = Fq(omega)**(-1)
    coeffs = _ntt_std(evals, inv_omega, q)
    d_inv = Fq(d)**(-1)
    # Times (1/d) which has not yet done
    return [c * d_inv for c in coeffs]


#
# NTT with X^d +1
#

def _ntt_neg(coeffs: list[int], psi: int, q: int) -> list[int]:
    """
    NTT with modulus polynomial X^d+1.
    In X^d+1 version, we uses roots=[\psi, \psi^3, \psi^5, \psi^7], where \psi is the primitive 2d-th roots of unity.
    It actually just works if we run ntt with `roots` since \psi^2=\psi^5^2 and so is \psi^3.
    But, we aren't able to run intt on the evals from ntt since intt needs every root w
    satisfying w^d=1. This doesn't hold if for \psi, \psi^3, ... .

    Twist trick: Instead, if we transform polynomial beforehand,
        a(x)    = a0 + a1*x^1 + ... to
        a_t(x)  = a0 + a1*psi*x^1+...
    and we use omega = \psi^2 as roots. We observe
        a_t(1)      = a(\psi)
        a_t(omega)  = a(\psi^3)
        ...
    and (omega^i)^4 = 1. It allows us to use intt. We just need to transform a_t to a.
    """
    Fq = GF(q)
    # Need to transform coeffs so we can reuse ntt
    transformed_coeffs = [Fq(c) * (psi**i) for i, c in enumerate(coeffs)]
    return _ntt_std(transformed_coeffs, psi**2, q)


def _intt_neg(evals: list[int], psi: int, q: int) -> list[int]:
    """
    We can derive the coeffs of a_t from [omega^i, ...] where omega=psi^2
    and transform a_t back to the original a
    """
    Fq = GF(q)
    a_t_coeffs = _intt_std(evals, Fq(psi)**2, q)
    psi_inv = Fq(psi)**(-1)
    return [c * (psi_inv**i) for i, c in enumerate(a_t_coeffs)]


def ntt(coeffs: list[int], Rq) -> list[int]:
    """
    Dispatch on Rq.modulus():
      - X^d - 1  → cyclic _ntt_std with primitive d-th root of unity
      - X^d + 1  → negacyclic _ntt_neg with primitive 2d-th root of unity
    """
    q = Rq.base_ring().order()
    modulus = Rq.modulus()
    d = modulus.degree()
    X = modulus.parent().gen()
    g = find_generator_from_mul_group(q)
    if modulus == X**d - 1:
        omega = find_root_of_unity(g, d, q)
        return _ntt_std(coeffs, omega, q)
    elif modulus == X**d + 1:
        psi = find_root_of_unity(g, 2*d, q)
        return _ntt_neg(coeffs, psi, q)
    else:
        raise ValueError(f"Unsupported modulus: {modulus}")


def intt(evals: list[int], Rq) -> list[int]:
    """
    Dispatch on Rq.modulus() (symmetric to ntt).
    """
    q = Rq.base_ring().order()
    modulus = Rq.modulus()
    d = modulus.degree()
    X = modulus.parent().gen()
    g = find_generator_from_mul_group(q)
    if modulus == X**d - 1:
        omega = find_root_of_unity(g, d, q)
        return _intt_std(evals, omega, q)
    elif modulus == X**d + 1:
        psi = find_root_of_unity(g, 2*d, q)
        return _intt_neg(evals, psi, q)
    else:
        raise ValueError(f"Unsupported modulus: {modulus}")


def _gen_random_Rq(Rq):
    import random as _random
    x = Rq.gen()
    q = Rq.base_ring().order()
    modulus = Rq.modulus()
    d = modulus.degree()
    return Rq(sum([(_random.randint(0, q-1)) * x**i for i in range(d)]))


def test_ntt_roundtrip(a, Rq):
    a_coeffs = a.list()
    a_evals_ntt = ntt(a_coeffs, Rq)
    print(f"{a_evals_ntt=}")

    # Test: evaluation form to coefficient form with INTT
    a_coeffs_roundtrip = intt(a_evals_ntt, Rq)
    assert a_coeffs_roundtrip == a_coeffs, f"INTT(NTT(poly)) != poly: {a_coeffs=}, {a_coeffs_roundtrip=}"

    # Test: multiplication in evaluation form and INTT back
    b = _gen_random_Rq(Rq)
    b_evals_ntt = ntt(b.list(), Rq)
    a_times_b_evals_ntt = [a_eval_w * b_eval_w for a_eval_w, b_eval_w in zip(a_evals_ntt, b_evals_ntt)]
    a_times_b_coeffs_roundtrip = intt(a_times_b_evals_ntt, Rq)
    expected_a_times_b = (a * b).list()
    assert a_times_b_coeffs_roundtrip == expected_a_times_b, f"a times b through NTT/INTT is not working: {expected_a_times_b=}, {a_times_b_coeffs_roundtrip=}"


def main():
    q = 17
    d = 4

    # q = 12289
    # d = 1024
    print(f"{q=}, {d=}")
    Fq = GF(q)
    R = PolynomialRing(Fq, 'X')
    X = R.gen()

    def test_ntt():
        Rq = R.quotient(X**d -1, 'x')
        a = _gen_random_Rq(Rq)
        a_coeffs = a.list()
        print(f"{a_coeffs=}")
        test_ntt_roundtrip(a, Rq)

    def test_ntt_neg():
        Rq = R.quotient(X**d+1, 'x')
        a = _gen_random_Rq(Rq)
        a_coeffs = a.list()
        print(f"{a_coeffs=}")
        test_ntt_roundtrip(a, Rq)

    test_ntt()
    test_ntt_neg()


if __name__ == "__main__":
    main()
