#!/usr/bin/env sage
from sage.all import *

# Exercise 2: NTT / INTT
# Ring: Z_17[X]/(X⁴ + 1), q=17, d=4
# Prerequisite: 17 ≡ 1 (mod 8), so a primitive 8th root of unity exists in Z_17

q = 17
d = 4
print(f"{q=}, {d=}")
Fq = GF(q)
R = PolynomialRing(Fq, 'X')
X = R.gen()


# Z_q^* = {1, ..., 16}, which is a cyclic group. First we find a generator
def find_generator_from_mul_group(q: int) -> int:
    # if q is prime, order is q-1.
    order = q-1
    # skip identity
    for g in range(2, order):
        generated_group = set([Fq(g**i) for i in range(order)])
        # group generated by g is Z_q^*
        if len(generated_group) == order:
            return Fq(g)
    assert g**(q - 1) == 1
    raise ValueError("couldn't find generator for U_q")


def find_root_of_unity(g: Fq, _d: int) -> Fq:
    assert g**(q - 1) == 1
    return g**((q-1) // _d)



def standard_ntt():
    """
    Rq is under X**d - 1 and we use the standard roots of unities
    """
    assert (q-1) % (d) == 0, f"q-1 is not divided by d, no primitive d-th root of unity. {q-1=}, {d=}"
    Rq = R.quotient(X**d - 1, 'x')
    x = Rq.gen()
    # g^{q-1} = 1
    g = find_generator_from_mul_group(q)
    print(f"{g=}")
    # find omega s.t. x^d = 1
    omega = find_root_of_unity(g, d)
    print(f"{omega=}")
    roots = [omega**i for i in range(d)]
    print(f"{roots=}")

    def gen_random_Rq() -> Rq:
        import random
        return Rq(sum([(random.randint(0, q-1)) * x**i for i in range(d)]))

    # coefficient form
    a = gen_random_Rq()
    a_coeffs = a.list()
    print(f"{a_coeffs=}")

    # Test: coefficient form to evaluation form with NTT
    # evaluation form (naive)
    expected_a_evals = [R(a.lift())(x) for x in roots]
    print(f"{expected_a_evals=}")

    def ntt(_coeffs: list[Fq], _roots: list[Fq]) -> list[Fq]:
        # recursion invairant
        # ntt(f, w) = ntt(f_even, w^2) + w*ntt(w_odd, w^2)
        cur_d = len(_coeffs)
        if cur_d == 1:
            return _coeffs

        f_even = [v for i, v in enumerate(_coeffs) if i % 2 == 0]
        f_odd = [v for i, v in enumerate(_coeffs) if i % 2 == 1]
        # f_even = sum([v* x**(i // 2) for i, v in enumerate(_coeffs) if i % 2 == 0])
        # f_odd = sum([v* x**(i // 2)for i, v in enumerate(_coeffs) if i % 2 == 1])
        # d = 4
        # v 1     -square->   1
        # v w     -square->   w^2
        #   w^2   -square->   w^4=1  (= 2 % (d/2) = 0)
        #   w^3   -square->   w^6=w^2 (= 3 % (d/2) = 1)
        # since (w^i)^2 = w^{i % {d/2}}, we only need to calculate f_o, f_e for the first half ([:d/2]),
        # and they can be reused for calculating the final results.
        next_roots = [_roots[i]**2 for i in range(cur_d // 2)]
        even_evals = ntt(f_even, next_roots)
        odd_evals = ntt(f_odd, next_roots)

        evals = [0] * cur_d
        for i in range(cur_d):
            w = _roots[i]
            w_square_eval_idx = i % (cur_d // 2)
            # f(w) = f_e(w^2) + w * f_o(w^2)
            evals[i] = even_evals[w_square_eval_idx] + w * odd_evals[w_square_eval_idx]
        return evals

    a_evals_ntt = ntt(a_coeffs, roots)
    assert a_evals_ntt == expected_a_evals, f"{a_evals_ntt=}, {expected_a_evals=}"

    def intt(evals: list[int], _roots: list[int]):
        f"""
        evaluation form <-> coefficient form is matrix multiplications
            coeff -> eval: [f(w^0), f(w^1)]^T = V * [f_0, f_1]^T
        since V is a dxd rank d matrix, it has inverse V^{-1}, and we get
            eval -> coeff: [f_0, f_1]^T = V^{-1} * [f(w^0), f(w^1)]^T

        V = [[1, 1], [1, w^1]] and V^{-1} = 1/d*[[1, 1], [1, w^{-1}]]
        It's just a matter of w^i -> w^{-i} and times 1/d
        If we treat eval ([f(w^0), f(w^1)]) as a polynomial, INTT is a
        linear transform with w^{-i} while the result should be timed `1/d`.

        NTT:    evals = ntt(coeffs, [1, w, ...])
        INTT:   coeffs = (1/d) * ntt(evals, [1, w^{-1}, ...])
        """
        # Treat evaluations as polynomial
        # Perform NTT with w^{-i}
        neg_roots = [r**(-1) for r in _roots]
        coeffs = ntt(evals, neg_roots)
        d_inv = Fq(d)**(-1)
        # Times (1/d) which has not yet done
        return [c * d_inv for c in coeffs]

    # Test: evaluation form to coefficient form with INTT
    a_coeffs_roundtrip = intt(a_evals_ntt, roots)
    assert a_coeffs_roundtrip == a_coeffs, f"INTT(NTT(poly)) != poly: {a_coeffs=}, {a_coeffs_roundtrip=}"

    # Test: multiplication in evaluation form and INTT back
    b = gen_random_Rq()
    b_evals_ntt = ntt(b.list(), roots)
    a_times_b_evals_ntt = [a_eval_w * b_eval_w for a_eval_w, b_eval_w in zip(a_evals_ntt, b_evals_ntt)]
    a_times_b_coeffs_roundtrip = intt(a_times_b_evals_ntt, roots)
    expected_a_times_b = (a * b).list()
    assert a_times_b_coeffs_roundtrip == expected_a_times_b, f"a times b through NTT/INTT is not working: {expected_a_times_b=}, {a_times_b_coeffs_roundtrip=}"


def negacyclic_ntt():
    assert (q-1) % (2*d) == 0, f"q-1 is not divided by 2d, no primitive 2d-th root of unity. {q-1=}, {d=}"
    R_q = R.quotient(X**d + 1, 'x')
    x = R_q.gen()

    #
    # Find roots of X^d + 1 = 0
    #
    # Z_q^* = {1, 2, ..., 2^{q-1}}, so we know 2^16 = 1 mod q,
    g = find_generator_from_mul_group(q)

    # g^{q-1} = 1, and we wanted to find an \omega s.t. \omega^{2d} = 1
    # so w = g^{(q-1)/(2d)} is the one.

    w = g ** ((q-1) / (2*d))
    assert w**(2*d) % q == 1
    roots = [w**i % q for i in range(2*d) if i % 2 == 1]



if __name__ == "__main__":
    standard_ntt()
